apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
spec:
  selector:
    app: hello-app
  ports:
  - name: http
    port: 85
    nodePort: 30080
    targetPort: 8080
  type: NodePort
status:
  loadBalancer: {}